import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
async function main() {
  await prisma.locations.createMany({
    //   // ======================
    //   // LOCATIONS
    //   // ======================
    data: [
      { id: 1, name: "Afghanistan", type: "country", parent_id: null },
      { id: 2, name: "Albania", type: "country", parent_id: null },
      { id: 3, name: "Algeria", type: "country", parent_id: null },
      { id: 4, name: "Andorra", type: "country", parent_id: null },
      { id: 5, name: "Angola", type: "country", parent_id: null },
      { id: 6, name: "Antigua and Barbuda", type: "country", parent_id: null },
      { id: 7, name: "Argentina", type: "country", parent_id: null },
      { id: 8, name: "Armenia", type: "country", parent_id: null },
      { id: 9, name: "Australia", type: "country", parent_id: null },
      { id: 10, name: "Austria", type: "country", parent_id: null },
      { id: 11, name: "Azerbaijan", type: "country", parent_id: null },
      { id: 12, name: "Bahamas", type: "country", parent_id: null },
      { id: 13, name: "Bahrain", type: "country", parent_id: null },
      { id: 14, name: "Bangladesh", type: "country", parent_id: null },
      { id: 15, name: "Barbados", type: "country", parent_id: null },
      { id: 16, name: "Belarus", type: "country", parent_id: null },
      { id: 17, name: "Belgium", type: "country", parent_id: null },
      { id: 18, name: "Belize", type: "country", parent_id: null },
      { id: 19, name: "Benin", type: "country", parent_id: null },
      { id: 20, name: "Bhutan", type: "country", parent_id: null },
      { id: 21, name: "Bolivia", type: "country", parent_id: null },
      {
        id: 22,
        name: "Bosnia and Herzegovina",
        type: "country",
        parent_id: null,
      },
      { id: 23, name: "Botswana", type: "country", parent_id: null },
      { id: 24, name: "Brazil", type: "country", parent_id: null },
      { id: 25, name: "Brunei Darussalam", type: "country", parent_id: null },
      { id: 26, name: "Bulgaria", type: "country", parent_id: null },
      { id: 27, name: "Burkina Faso", type: "country", parent_id: null },
      { id: 28, name: "Burundi", type: "country", parent_id: null },
      { id: 29, name: "Cabo Verde", type: "country", parent_id: null },
      { id: 30, name: "Cambodia", type: "country", parent_id: null },
      { id: 31, name: "Cameroon", type: "country", parent_id: null },
      { id: 32, name: "Canada", type: "country", parent_id: null },
      {
        id: 33,
        name: "Central African Republic",
        type: "country",
        parent_id: null,
      },
      { id: 34, name: "Chad", type: "country", parent_id: null },
      { id: 35, name: "Chile", type: "country", parent_id: null },
      { id: 36, name: "China", type: "country", parent_id: null },
      { id: 37, name: "Colombia", type: "country", parent_id: null },
      { id: 38, name: "Comoros", type: "country", parent_id: null },
      {
        id: 39,
        name: "Congo (Democratic Republic)",
        type: "country",
        parent_id: null,
      },
      { id: 40, name: "Congo (Republic)", type: "country", parent_id: null },
      { id: 41, name: "Costa Rica", type: "country", parent_id: null },
      { id: 42, name: "Croatia", type: "country", parent_id: null },
      { id: 43, name: "Cuba", type: "country", parent_id: null },
      { id: 44, name: "Cyprus", type: "country", parent_id: null },
      { id: 45, name: "Czechia", type: "country", parent_id: null },
      { id: 46, name: "Denmark", type: "country", parent_id: null },
      { id: 47, name: "Djibouti", type: "country", parent_id: null },
      { id: 48, name: "Dominica", type: "country", parent_id: null },
      { id: 49, name: "Dominican Republic", type: "country", parent_id: null },
      { id: 50, name: "Ecuador", type: "country", parent_id: null },
      { id: 51, name: "Egypt", type: "country", parent_id: null },
      { id: 52, name: "El Salvador", type: "country", parent_id: null },
      { id: 53, name: "Equatorial Guinea", type: "country", parent_id: null },
      { id: 54, name: "Eritrea", type: "country", parent_id: null },
      { id: 55, name: "Estonia", type: "country", parent_id: null },
      { id: 56, name: "Eswatini", type: "country", parent_id: null },
      { id: 57, name: "Ethiopia", type: "country", parent_id: null },
      { id: 58, name: "Fiji", type: "country", parent_id: null },
      { id: 59, name: "Finland", type: "country", parent_id: null },
      { id: 60, name: "France", type: "country", parent_id: null },
      { id: 61, name: "Gabon", type: "country", parent_id: null },
      { id: 62, name: "Gambia", type: "country", parent_id: null },
      { id: 63, name: "Georgia", type: "country", parent_id: null },
      { id: 64, name: "Germany", type: "country", parent_id: null },
      { id: 65, name: "Ghana", type: "country", parent_id: null },
      { id: 66, name: "Greece", type: "country", parent_id: null },
      { id: 67, name: "Grenada", type: "country", parent_id: null },
      { id: 68, name: "Guatemala", type: "country", parent_id: null },
      { id: 69, name: "Guinea", type: "country", parent_id: null },
      { id: 70, name: "Guinea-Bissau", type: "country", parent_id: null },
      { id: 71, name: "Guyana", type: "country", parent_id: null },
      { id: 72, name: "Haiti", type: "country", parent_id: null },
      { id: 73, name: "Honduras", type: "country", parent_id: null },
      { id: 74, name: "Hungary", type: "country", parent_id: null },
      { id: 75, name: "Iceland", type: "country", parent_id: null },
      { id: 76, name: "India", type: "country", parent_id: null },
      { id: 77, name: "Indonesia", type: "country", parent_id: null },
      { id: 78, name: "Iran", type: "country", parent_id: null },
      { id: 79, name: "Iraq", type: "country", parent_id: null },
      { id: 80, name: "Ireland", type: "country", parent_id: null },
      { id: 81, name: "Israel", type: "country", parent_id: null },
      { id: 82, name: "Italy", type: "country", parent_id: null },
      { id: 83, name: "Ivory Coast", type: "country", parent_id: null },
      { id: 84, name: "Jamaica", type: "country", parent_id: null },
      { id: 85, name: "Japan", type: "country", parent_id: null },
      { id: 86, name: "Jordan", type: "country", parent_id: null },
      { id: 87, name: "Kazakhstan", type: "country", parent_id: null },
      { id: 88, name: "Kenya", type: "country", parent_id: null },
      { id: 89, name: "Kiribati", type: "country", parent_id: null },
      { id: 90, name: "Korea (North)", type: "country", parent_id: null },
      { id: 91, name: "Korea (South)", type: "country", parent_id: null },
      { id: 92, name: "Kuwait", type: "country", parent_id: null },
      { id: 93, name: "Kyrgyzstan", type: "country", parent_id: null },
      { id: 94, name: "Laos", type: "country", parent_id: null },
      { id: 95, name: "Latvia", type: "country", parent_id: null },
      { id: 96, name: "Lebanon", type: "country", parent_id: null },
      { id: 97, name: "Lesotho", type: "country", parent_id: null },
      { id: 98, name: "Liberia", type: "country", parent_id: null },
      { id: 99, name: "Libya", type: "country", parent_id: null },
      { id: 100, name: "Liechtenstein", type: "country", parent_id: null },
      { id: 101, name: "Lithuania", type: "country", parent_id: null },
      { id: 102, name: "Luxembourg", type: "country", parent_id: null },
      { id: 103, name: "Madagascar", type: "country", parent_id: null },
      { id: 104, name: "Malawi", type: "country", parent_id: null },
      { id: 105, name: "Malaysia", type: "country", parent_id: null },
      { id: 106, name: "Maldives", type: "country", parent_id: null },
      { id: 107, name: "Mali", type: "country", parent_id: null },
      { id: 108, name: "Malta", type: "country", parent_id: null },
      { id: 109, name: "Marshall Islands", type: "country", parent_id: null },
      { id: 110, name: "Mauritania", type: "country", parent_id: null },
      { id: 111, name: "Mauritius", type: "country", parent_id: null },
      { id: 112, name: "Mexico", type: "country", parent_id: null },
      { id: 113, name: "Micronesia", type: "country", parent_id: null },
      { id: 114, name: "Moldova", type: "country", parent_id: null },
      { id: 115, name: "Monaco", type: "country", parent_id: null },
      { id: 116, name: "Mongolia", type: "country", parent_id: null },
      { id: 117, name: "Montenegro", type: "country", parent_id: null },
      { id: 118, name: "Morocco", type: "country", parent_id: null },
      { id: 119, name: "Mozambique", type: "country", parent_id: null },
      { id: 120, name: "Myanmar", type: "country", parent_id: null },
      { id: 121, name: "Namibia", type: "country", parent_id: null },
      { id: 122, name: "Nauru", type: "country", parent_id: null },
      { id: 123, name: "Nepal", type: "country", parent_id: null },
      { id: 124, name: "Netherlands", type: "country", parent_id: null },
      { id: 125, name: "New Zealand", type: "country", parent_id: null },
      { id: 126, name: "Nicaragua", type: "country", parent_id: null },
      { id: 127, name: "Niger", type: "country", parent_id: null },
      { id: 128, name: "Nigeria", type: "country", parent_id: null },
      { id: 129, name: "North Macedonia", type: "country", parent_id: null },
      { id: 130, name: "Norway", type: "country", parent_id: null },
      { id: 131, name: "Oman", type: "country", parent_id: null },
      { id: 132, name: "Pakistan", type: "country", parent_id: null },
      { id: 133, name: "Palau", type: "country", parent_id: null },
      { id: 134, name: "Panama", type: "country", parent_id: null },
      { id: 135, name: "Papua New Guinea", type: "country", parent_id: null },
      { id: 136, name: "Paraguay", type: "country", parent_id: null },
      { id: 137, name: "Peru", type: "country", parent_id: null },
      { id: 138, name: "Philippines", type: "country", parent_id: null },
      { id: 139, name: "Poland", type: "country", parent_id: null },
      { id: 140, name: "Portugal", type: "country", parent_id: null },
      { id: 141, name: "Qatar", type: "country", parent_id: null },
      { id: 142, name: "Romania", type: "country", parent_id: null },
      { id: 143, name: "Russia", type: "country", parent_id: null },
      { id: 144, name: "Rwanda", type: "country", parent_id: null },
      {
        id: 145,
        name: "Saint Kitts and Nevis",
        type: "country",
        parent_id: null,
      },
      { id: 146, name: "Saint Lucia", type: "country", parent_id: null },
      {
        id: 147,
        name: "Saint Vincent and the Grenadines",
        type: "country",
        parent_id: null,
      },
      { id: 148, name: "Samoa", type: "country", parent_id: null },
      { id: 149, name: "San Marino", type: "country", parent_id: null },
      {
        id: 150,
        name: "Sao Tome and Principe",
        type: "country",
        parent_id: null,
      },
      { id: 151, name: "Saudi Arabia", type: "country", parent_id: null },
      { id: 152, name: "Senegal", type: "country", parent_id: null },
      { id: 153, name: "Serbia", type: "country", parent_id: null },
      { id: 154, name: "Seychelles", type: "country", parent_id: null },
      { id: 155, name: "Sierra Leone", type: "country", parent_id: null },
      { id: 156, name: "Singapore", type: "country", parent_id: null },
      { id: 157, name: "Slovakia", type: "country", parent_id: null },
      { id: 158, name: "Slovenia", type: "country", parent_id: null },
      { id: 159, name: "Solomon Islands", type: "country", parent_id: null },
      { id: 160, name: "Somalia", type: "country", parent_id: null },
      { id: 161, name: "South Africa", type: "country", parent_id: null },
      { id: 162, name: "South Sudan", type: "country", parent_id: null },
      { id: 163, name: "Spain", type: "country", parent_id: null },
      { id: 164, name: "Sri Lanka", type: "country", parent_id: null },
      { id: 165, name: "Sudan", type: "country", parent_id: null },
      { id: 166, name: "Suriname", type: "country", parent_id: null },
      { id: 167, name: "Sweden", type: "country", parent_id: null },
      { id: 168, name: "Switzerland", type: "country", parent_id: null },
      { id: 169, name: "Syria", type: "country", parent_id: null },
      { id: 170, name: "Taiwan", type: "country", parent_id: null },
      { id: 171, name: "Tajikistan", type: "country", parent_id: null },
      { id: 172, name: "Tanzania", type: "country", parent_id: null },
      { id: 173, name: "Thailand", type: "country", parent_id: null },
      { id: 174, name: "Timor-Leste", type: "country", parent_id: null },
      { id: 175, name: "Togo", type: "country", parent_id: null },
      { id: 176, name: "Tonga", type: "country", parent_id: null },
      {
        id: 177,
        name: "Trinidad and Tobago",
        type: "country",
        parent_id: null,
      },
      { id: 178, name: "Tunisia", type: "country", parent_id: null },
      { id: 179, name: "Turkey", type: "country", parent_id: null },
      { id: 180, name: "Turkmenistan", type: "country", parent_id: null },
      { id: 181, name: "Tuvalu", type: "country", parent_id: null },
      { id: 182, name: "Uganda", type: "country", parent_id: null },
      { id: 183, name: "Ukraine", type: "country", parent_id: null },
      {
        id: 184,
        name: "United Arab Emirates",
        type: "country",
        parent_id: null,
      },
      { id: 185, name: "United Kingdom", type: "country", parent_id: null },
      {
        id: 186,
        name: "United States of America",
        type: "country",
        parent_id: null,
      },
      { id: 187, name: "Uruguay", type: "country", parent_id: null },
      { id: 188, name: "Uzbekistan", type: "country", parent_id: null },
      { id: 189, name: "Vanuatu", type: "country", parent_id: null },
      { id: 190, name: "Vatican City", type: "country", parent_id: null },
      { id: 191, name: "Venezuela", type: "country", parent_id: null },
      { id: 192, name: "Vietnam", type: "country", parent_id: null },
      { id: 193, name: "Yemen", type: "country", parent_id: null },
      { id: 194, name: "Zambia", type: "country", parent_id: null },
      { id: 195, name: "Zimbabwe", type: "country", parent_id: null },

      { id: 196, name: "Abia", type: "state", parent_id: 128 },
      { id: 197, name: "Adamawa", type: "state", parent_id: 128 },
      { id: 198, name: "Akwa Ibom", type: "state", parent_id: 128 },
      { id: 199, name: "Anambra", type: "state", parent_id: 128 },
      { id: 200, name: "Bauchi", type: "state", parent_id: 128 },
      { id: 201, name: "Bayelsa", type: "state", parent_id: 128 },
      { id: 202, name: "Benue", type: "state", parent_id: 128 },
      { id: 203, name: "Borno", type: "state", parent_id: 128 },
      { id: 204, name: "Cross River", type: "state", parent_id: 128 },
      { id: 205, name: "Delta", type: "state", parent_id: 128 },
      { id: 206, name: "Ebonyi", type: "state", parent_id: 128 },
      { id: 207, name: "Edo", type: "state", parent_id: 128 },
      { id: 208, name: "Ekiti", type: "state", parent_id: 128 },
      { id: 209, name: "Enugu", type: "state", parent_id: 128 },
      {
        id: 210,
        name: "Federal Capital Territory",
        type: "state",
        parent_id: 128,
      },
      { id: 211, name: "Gombe", type: "state", parent_id: 128 },
      { id: 212, name: "Imo", type: "state", parent_id: 128 },
      { id: 213, name: "Jigawa", type: "state", parent_id: 128 },
      { id: 214, name: "Kaduna", type: "state", parent_id: 128 },
      { id: 215, name: "Kano", type: "state", parent_id: 128 },
      { id: 216, name: "Katsina", type: "state", parent_id: 128 },
      { id: 217, name: "Kebbi", type: "state", parent_id: 128 },
      { id: 218, name: "Kogi", type: "state", parent_id: 128 },
      { id: 219, name: "Kwara", type: "state", parent_id: 128 },
      { id: 220, name: "Lagos", type: "state", parent_id: 128 },
      { id: 221, name: "Nasarawa", type: "state", parent_id: 128 },
      { id: 222, name: "Niger", type: "state", parent_id: 128 },
      { id: 223, name: "Ogun", type: "state", parent_id: 128 },
      { id: 224, name: "Ondo", type: "state", parent_id: 128 },
      { id: 225, name: "Osun", type: "state", parent_id: 128 },
      { id: 226, name: "Oyo", type: "state", parent_id: 128 },
      { id: 227, name: "Plateau", type: "state", parent_id: 128 },
      { id: 228, name: "Rivers", type: "state", parent_id: 128 },
      { id: 229, name: "Sokoto", type: "state", parent_id: 128 },
      { id: 230, name: "Taraba", type: "state", parent_id: 128 },
      { id: 231, name: "Yobe", type: "state", parent_id: 128 },
      { id: 232, name: "Zamfara", type: "state", parent_id: 128 },

      { id: 233, name: "Aba North", type: "lga", parent_id: 196 },
      { id: 234, name: "Aba South", type: "lga", parent_id: 196 },
      { id: 235, name: "Arochukwu", type: "lga", parent_id: 196 },
      { id: 236, name: "Bende", type: "lga", parent_id: 196 },
      { id: 237, name: "Ikwuano", type: "lga", parent_id: 196 },
      { id: 238, name: "Isiala Ngwa North", type: "lga", parent_id: 196 },
      { id: 239, name: "Isiala Ngwa South", type: "lga", parent_id: 196 },
      { id: 240, name: "Isuikwuato", type: "lga", parent_id: 196 },
      { id: 241, name: "Obi Ngwa", type: "lga", parent_id: 196 },
      { id: 242, name: "Ohafia", type: "lga", parent_id: 196 },
      { id: 243, name: "Osisioma", type: "lga", parent_id: 196 },
      { id: 244, name: "Ugwunagbo", type: "lga", parent_id: 196 },
      { id: 245, name: "Ukwa East", type: "lga", parent_id: 196 },
      { id: 246, name: "Ukwa West", type: "lga", parent_id: 196 },
      { id: 247, name: "Umuahia North", type: "lga", parent_id: 196 },
      { id: 248, name: "Umuahia South", type: "lga", parent_id: 196 },
      { id: 249, name: "Umu Nneochi", type: "lga", parent_id: 196 },

      { id: 250, name: "Demsa", type: "lga", parent_id: 197 },
      { id: 251, name: "Fufore", type: "lga", parent_id: 197 },
      { id: 252, name: "Ganye", type: "lga", parent_id: 197 },
      { id: 253, name: "Girei", type: "lga", parent_id: 197 },
      { id: 254, name: "Gombi", type: "lga", parent_id: 197 },
      { id: 255, name: "Guyuk", type: "lga", parent_id: 197 },
      { id: 256, name: "Hong", type: "lga", parent_id: 197 },
      { id: 257, name: "Jada", type: "lga", parent_id: 197 },
      { id: 258, name: "Lamurde", type: "lga", parent_id: 197 },
      { id: 259, name: "Madagali", type: "lga", parent_id: 197 },
      { id: 260, name: "Maiha", type: "lga", parent_id: 197 },
      { id: 261, name: "Mayo-Belwa", type: "lga", parent_id: 197 },
      { id: 262, name: "Michika", type: "lga", parent_id: 197 },
      { id: 263, name: "Mubi North", type: "lga", parent_id: 197 },
      { id: 264, name: "Mubi South", type: "lga", parent_id: 197 },
      { id: 265, name: "Numan", type: "lga", parent_id: 197 },
      { id: 266, name: "Shelleng", type: "lga", parent_id: 197 },
      { id: 267, name: "Song", type: "lga", parent_id: 197 },
      { id: 268, name: "Toungo", type: "lga", parent_id: 197 },
      { id: 269, name: "Yola North", type: "lga", parent_id: 197 },
      { id: 270, name: "Yola South", type: "lga", parent_id: 197 },

      { id: 271, name: "Abak", type: "lga", parent_id: 198 },
      { id: 272, name: "Eastern Obolo", type: "lga", parent_id: 198 },
      { id: 273, name: "Eket", type: "lga", parent_id: 198 },
      { id: 274, name: "Esit Eket", type: "lga", parent_id: 198 },
      { id: 275, name: "Essien Udim", type: "lga", parent_id: 198 },
      { id: 276, name: "Etim Ekpo", type: "lga", parent_id: 198 },
      { id: 277, name: "Etinan", type: "lga", parent_id: 198 },
      { id: 278, name: "Ibeno", type: "lga", parent_id: 198 },
      { id: 279, name: "Ibesikpo Asutan", type: "lga", parent_id: 198 },
      { id: 280, name: "Ibiono-Ibom", type: "lga", parent_id: 198 },
      { id: 281, name: "Ika", type: "lga", parent_id: 198 },
      { id: 282, name: "Ikono", type: "lga", parent_id: 198 },
      { id: 283, name: "Ikot Abasi", type: "lga", parent_id: 198 },
      { id: 284, name: "Ikot Ekpene", type: "lga", parent_id: 198 },
      { id: 285, name: "Ini", type: "lga", parent_id: 198 },
      { id: 286, name: "Itu", type: "lga", parent_id: 198 },
      { id: 287, name: "Mbo", type: "lga", parent_id: 198 },
      { id: 288, name: "Mkpat-Enin", type: "lga", parent_id: 198 },
      { id: 289, name: "Nsit-Atai", type: "lga", parent_id: 198 },
      { id: 290, name: "Nsit-Ibom", type: "lga", parent_id: 198 },
      { id: 291, name: "Nsit-Ubium", type: "lga", parent_id: 198 },
      { id: 292, name: "Obot Akara", type: "lga", parent_id: 198 },
      { id: 293, name: "Okobo", type: "lga", parent_id: 198 },
      { id: 294, name: "Onna", type: "lga", parent_id: 198 },
      { id: 295, name: "Oron", type: "lga", parent_id: 198 },
      { id: 296, name: "Oruk Anam", type: "lga", parent_id: 198 },
      { id: 297, name: "Udung-Uko", type: "lga", parent_id: 198 },
      { id: 298, name: "Ukanafun", type: "lga", parent_id: 198 },
      { id: 299, name: "Uruan", type: "lga", parent_id: 198 },
      { id: 300, name: "Urue-Offong/Oruko", type: "lga", parent_id: 198 },
      { id: 301, name: "Uyo", type: "lga", parent_id: 198 },

      { id: 302, name: "Aguata", type: "lga", parent_id: 199 },
      { id: 303, name: "Anambra East", type: "lga", parent_id: 199 },
      { id: 304, name: "Anambra West", type: "lga", parent_id: 199 },
      { id: 305, name: "Anaocha", type: "lga", parent_id: 199 },
      { id: 306, name: "Awka North", type: "lga", parent_id: 199 },
      { id: 307, name: "Awka South", type: "lga", parent_id: 199 },
      { id: 308, name: "Ayamelum", type: "lga", parent_id: 199 },
      { id: 309, name: "Dunukofia", type: "lga", parent_id: 199 },
      { id: 310, name: "Ekwusigo", type: "lga", parent_id: 199 },
      { id: 311, name: "Idemili North", type: "lga", parent_id: 199 },
      { id: 312, name: "Idemili South", type: "lga", parent_id: 199 },
      { id: 313, name: "Ihiala", type: "lga", parent_id: 199 },
      { id: 314, name: "Njikoka", type: "lga", parent_id: 199 },
      { id: 315, name: "Nnewi North", type: "lga", parent_id: 199 },
      { id: 316, name: "Nnewi South", type: "lga", parent_id: 199 },
      { id: 317, name: "Ogbaru", type: "lga", parent_id: 199 },
      { id: 318, name: "Onitsha North", type: "lga", parent_id: 199 },
      { id: 319, name: "Onitsha South", type: "lga", parent_id: 199 },
      { id: 320, name: "Orumba North", type: "lga", parent_id: 199 },
      { id: 321, name: "Orumba South", type: "lga", parent_id: 199 },
      { id: 322, name: "Oyi", type: "lga", parent_id: 199 },

      { id: 323, name: "Alkaleri", type: "lga", parent_id: 200 },
      { id: 324, name: "Bauchi", type: "lga", parent_id: 200 },
      { id: 325, name: "Bogoro", type: "lga", parent_id: 200 },
      { id: 326, name: "Damban", type: "lga", parent_id: 200 },
      { id: 327, name: "Darazo", type: "lga", parent_id: 200 },
      { id: 328, name: "Dass", type: "lga", parent_id: 200 },
      { id: 329, name: "Gamawa", type: "lga", parent_id: 200 },
      { id: 330, name: "Ganjuwa", type: "lga", parent_id: 200 },
      { id: 331, name: "Giade", type: "lga", parent_id: 200 },
      { id: 332, name: "Itas/Gadau", type: "lga", parent_id: 200 },
      { id: 333, name: "Jama'are", type: "lga", parent_id: 200 },
      { id: 334, name: "Katagum", type: "lga", parent_id: 200 },
      { id: 335, name: "Kirfi", type: "lga", parent_id: 200 },
      { id: 336, name: "Misau", type: "lga", parent_id: 200 },
      { id: 337, name: "Ningi", type: "lga", parent_id: 200 },
      { id: 338, name: "Shira", type: "lga", parent_id: 200 },
      { id: 339, name: "Tafawa Balewa", type: "lga", parent_id: 200 },
      { id: 340, name: "Toro", type: "lga", parent_id: 200 },
      { id: 341, name: "Warji", type: "lga", parent_id: 200 },
      { id: 342, name: "Zaki", type: "lga", parent_id: 200 },

      { id: 343, name: "Brass", type: "lga", parent_id: 201 },
      { id: 344, name: "Ekeremor", type: "lga", parent_id: 201 },
      { id: 345, name: "Kolokuma/Opokuma", type: "lga", parent_id: 201 },
      { id: 346, name: "Nembe", type: "lga", parent_id: 201 },
      { id: 347, name: "Ogbia", type: "lga", parent_id: 201 },
      { id: 348, name: "Sagbama", type: "lga", parent_id: 201 },
      { id: 349, name: "Southern Ijaw", type: "lga", parent_id: 201 },
      { id: 350, name: "Yenagoa", type: "lga", parent_id: 201 },

      { id: 351, name: "Ado", type: "lga", parent_id: 202 },
      { id: 352, name: "Agatu", type: "lga", parent_id: 202 },
      { id: 353, name: "Apa", type: "lga", parent_id: 202 },
      { id: 354, name: "Buruku", type: "lga", parent_id: 202 },
      { id: 355, name: "Gboko", type: "lga", parent_id: 202 },
      { id: 356, name: "Guma", type: "lga", parent_id: 202 },
      { id: 357, name: "Gwer East", type: "lga", parent_id: 202 },
      { id: 358, name: "Gwer West", type: "lga", parent_id: 202 },
      { id: 359, name: "Katsina-Ala", type: "lga", parent_id: 202 },
      { id: 360, name: "Konshisha", type: "lga", parent_id: 202 },
      { id: 361, name: "Kwande", type: "lga", parent_id: 202 },
      { id: 362, name: "Logo", type: "lga", parent_id: 202 },
      { id: 363, name: "Makurdi", type: "lga", parent_id: 202 },
      { id: 364, name: "Obi", type: "lga", parent_id: 202 },
      { id: 365, name: "Ogbadibo", type: "lga", parent_id: 202 },
      { id: 366, name: "Ohimini", type: "lga", parent_id: 202 },
      { id: 367, name: "Oju", type: "lga", parent_id: 202 },
      { id: 368, name: "Okpokwu", type: "lga", parent_id: 202 },
      { id: 369, name: "Otukpo", type: "lga", parent_id: 202 },
      { id: 370, name: "Tarka", type: "lga", parent_id: 202 },
      { id: 371, name: "Ukum", type: "lga", parent_id: 202 },
      { id: 372, name: "Ushongo", type: "lga", parent_id: 202 },
      { id: 373, name: "Vandeikya", type: "lga", parent_id: 202 },

      { id: 374, name: "Abadam", type: "lga", parent_id: 203 },
      { id: 375, name: "Askira/Uba", type: "lga", parent_id: 203 },
      { id: 376, name: "Bama", type: "lga", parent_id: 203 },
      { id: 377, name: "Bayo", type: "lga", parent_id: 203 },
      { id: 378, name: "Biu", type: "lga", parent_id: 203 },
      { id: 379, name: "Chibok", type: "lga", parent_id: 203 },
      { id: 380, name: "Damboa", type: "lga", parent_id: 203 },
      { id: 381, name: "Dikwa", type: "lga", parent_id: 203 },
      { id: 382, name: "Gubio", type: "lga", parent_id: 203 },
      { id: 383, name: "Guzamala", type: "lga", parent_id: 203 },
      { id: 384, name: "Gwoza", type: "lga", parent_id: 203 },
      { id: 385, name: "Hawul", type: "lga", parent_id: 203 },
      { id: 386, name: "Jere", type: "lga", parent_id: 203 },
      { id: 387, name: "Kaga", type: "lga", parent_id: 203 },
      { id: 388, name: "Kala/Balge", type: "lga", parent_id: 203 },
      { id: 389, name: "Konduga", type: "lga", parent_id: 203 },
      { id: 390, name: "Kukawa", type: "lga", parent_id: 203 },
      { id: 391, name: "Kwaya Kusar", type: "lga", parent_id: 203 },
      { id: 392, name: "Mafa", type: "lga", parent_id: 203 },
      { id: 393, name: "Magumeri", type: "lga", parent_id: 203 },
      { id: 394, name: "Maiduguri", type: "lga", parent_id: 203 },
      { id: 395, name: "Marte", type: "lga", parent_id: 203 },
      { id: 396, name: "Mobbar", type: "lga", parent_id: 203 },
      { id: 397, name: "Monguno", type: "lga", parent_id: 203 },
      { id: 398, name: "Ngala", type: "lga", parent_id: 203 },
      { id: 399, name: "Nganzai", type: "lga", parent_id: 203 },
      { id: 400, name: "Shani", type: "lga", parent_id: 203 },

      { id: 401, name: "Abi", type: "lga", parent_id: 204 },
      { id: 402, name: "Akamkpa", type: "lga", parent_id: 204 },
      { id: 403, name: "Akpabuyo", type: "lga", parent_id: 204 },
      { id: 404, name: "Bakassi", type: "lga", parent_id: 204 },
      { id: 405, name: "Bekwarra", type: "lga", parent_id: 204 },
      { id: 406, name: "Biase", type: "lga", parent_id: 204 },
      { id: 407, name: "Boki", type: "lga", parent_id: 204 },
      { id: 408, name: "Calabar Municipal", type: "lga", parent_id: 204 },
      { id: 409, name: "Calabar South", type: "lga", parent_id: 204 },
      { id: 410, name: "Etung", type: "lga", parent_id: 204 },
      { id: 411, name: "Ikom", type: "lga", parent_id: 204 },
      { id: 412, name: "Obanliku", type: "lga", parent_id: 204 },
      { id: 413, name: "Obubra", type: "lga", parent_id: 204 },
      { id: 414, name: "Obudu", type: "lga", parent_id: 204 },
      { id: 415, name: "Odukpani", type: "lga", parent_id: 204 },
      { id: 416, name: "Ogoja", type: "lga", parent_id: 204 },
      { id: 417, name: "Yakurr", type: "lga", parent_id: 204 },
      { id: 418, name: "Yala", type: "lga", parent_id: 204 },

      { id: 419, name: "Aniocha North", type: "lga", parent_id: 205 },
      { id: 420, name: "Aniocha South", type: "lga", parent_id: 205 },
      { id: 421, name: "Bomadi", type: "lga", parent_id: 205 },
      { id: 422, name: "Burutu", type: "lga", parent_id: 205 },
      { id: 423, name: "Ethiope East", type: "lga", parent_id: 205 },
      { id: 424, name: "Ethiope West", type: "lga", parent_id: 205 },
      { id: 425, name: "Ika North East", type: "lga", parent_id: 205 },
      { id: 426, name: "Ika South", type: "lga", parent_id: 205 },
      { id: 427, name: "Isoko North", type: "lga", parent_id: 205 },
      { id: 428, name: "Isoko South", type: "lga", parent_id: 205 },
      { id: 429, name: "Ndokwa East", type: "lga", parent_id: 205 },
      { id: 430, name: "Ndokwa West", type: "lga", parent_id: 205 },
      { id: 431, name: "Okpe", type: "lga", parent_id: 205 },
      { id: 432, name: "Oshimili North", type: "lga", parent_id: 205 },
      { id: 433, name: "Oshimili South", type: "lga", parent_id: 205 },
      { id: 434, name: "Patani", type: "lga", parent_id: 205 },
      { id: 435, name: "Sapele", type: "lga", parent_id: 205 },
      { id: 436, name: "Udu", type: "lga", parent_id: 205 },
      { id: 437, name: "Ughelli North", type: "lga", parent_id: 205 },
      { id: 438, name: "Ughelli South", type: "lga", parent_id: 205 },
      { id: 439, name: "Ukwuani", type: "lga", parent_id: 205 },
      { id: 440, name: "Uvwie", type: "lga", parent_id: 205 },
      { id: 441, name: "Warri North", type: "lga", parent_id: 205 },
      { id: 442, name: "Warri South", type: "lga", parent_id: 205 },
      { id: 443, name: "Warri South West", type: "lga", parent_id: 205 },

      { id: 444, name: "Abakaliki", type: "lga", parent_id: 206 },
      { id: 445, name: "Afikpo North", type: "lga", parent_id: 206 },
      { id: 446, name: "Afikpo South", type: "lga", parent_id: 206 },
      { id: 447, name: "Ebonyi", type: "lga", parent_id: 206 },
      { id: 448, name: "Ezza North", type: "lga", parent_id: 206 },
      { id: 449, name: "Ezza South", type: "lga", parent_id: 206 },
      { id: 450, name: "Ikwo", type: "lga", parent_id: 206 },
      { id: 451, name: "Ishielu", type: "lga", parent_id: 206 },
      { id: 452, name: "Ivo", type: "lga", parent_id: 206 },
      { id: 453, name: "Izzi", type: "lga", parent_id: 206 },
      { id: 454, name: "Ohaozara", type: "lga", parent_id: 206 },
      { id: 455, name: "Ohaukwu", type: "lga", parent_id: 206 },
      { id: 456, name: "Onicha", type: "lga", parent_id: 206 },

      { id: 457, name: "Akoko-Edo", type: "lga", parent_id: 207 },
      { id: 458, name: "Egor", type: "lga", parent_id: 207 },
      { id: 459, name: "Esan Central", type: "lga", parent_id: 207 },
      { id: 460, name: "Esan North-East", type: "lga", parent_id: 207 },
      { id: 461, name: "Esan South-East", type: "lga", parent_id: 207 },
      { id: 462, name: "Esan West", type: "lga", parent_id: 207 },
      { id: 463, name: "Etsako Central", type: "lga", parent_id: 207 },
      { id: 464, name: "Etsako East", type: "lga", parent_id: 207 },
      { id: 465, name: "Etsako West", type: "lga", parent_id: 207 },
      { id: 466, name: "Igueben", type: "lga", parent_id: 207 },
      { id: 467, name: "Ikpoba-Okha", type: "lga", parent_id: 207 },
      { id: 468, name: "Orhionmwon", type: "lga", parent_id: 207 },
      { id: 469, name: "Oredo", type: "lga", parent_id: 207 },
      { id: 470, name: "Ovia North-East", type: "lga", parent_id: 207 },
      { id: 471, name: "Ovia South-West", type: "lga", parent_id: 207 },
      { id: 472, name: "Owan East", type: "lga", parent_id: 207 },
      { id: 473, name: "Owan West", type: "lga", parent_id: 207 },
      { id: 474, name: "Uhunmwonde", type: "lga", parent_id: 207 },

      { id: 475, name: "Ado-Ekiti", type: "lga", parent_id: 208 },
      { id: 476, name: "Efon", type: "lga", parent_id: 208 },
      { id: 477, name: "Ekiti East", type: "lga", parent_id: 208 },
      { id: 478, name: "Ekiti South-West", type: "lga", parent_id: 208 },
      { id: 479, name: "Ekiti West", type: "lga", parent_id: 208 },
      { id: 480, name: "Emure", type: "lga", parent_id: 208 },
      { id: 481, name: "Gbonyin", type: "lga", parent_id: 208 },
      { id: 482, name: "Ido-Osi", type: "lga", parent_id: 208 },
      { id: 483, name: "Ijero", type: "lga", parent_id: 208 },
      { id: 484, name: "Ikere", type: "lga", parent_id: 208 },
      { id: 485, name: "Ikole", type: "lga", parent_id: 208 },
      { id: 486, name: "Ilejemeje", type: "lga", parent_id: 208 },
      { id: 487, name: "Irepodun/Ifelodun", type: "lga", parent_id: 208 },
      { id: 488, name: "Ise/Orun", type: "lga", parent_id: 208 },
      { id: 489, name: "Moba", type: "lga", parent_id: 208 },
      { id: 490, name: "Oye", type: "lga", parent_id: 208 },

      { id: 491, name: "Aninri", type: "lga", parent_id: 209 },
      { id: 492, name: "Awgu", type: "lga", parent_id: 209 },
      { id: 493, name: "Enugu East", type: "lga", parent_id: 209 },
      { id: 494, name: "Enugu North", type: "lga", parent_id: 209 },
      { id: 495, name: "Enugu South", type: "lga", parent_id: 209 },
      { id: 496, name: "Ezeagu", type: "lga", parent_id: 209 },
      { id: 497, name: "Igbo-Etiti", type: "lga", parent_id: 209 },
      { id: 498, name: "Igbo-Eze North", type: "lga", parent_id: 209 },
      { id: 499, name: "Igbo-Eze South", type: "lga", parent_id: 209 },
      { id: 500, name: "Isi-Uzo", type: "lga", parent_id: 209 },
      { id: 501, name: "Nkanu East", type: "lga", parent_id: 209 },
      { id: 502, name: "Nkanu West", type: "lga", parent_id: 209 },
      { id: 503, name: "Nsukka", type: "lga", parent_id: 209 },
      { id: 504, name: "Oji River", type: "lga", parent_id: 209 },
      { id: 505, name: "Udenu", type: "lga", parent_id: 209 },
      { id: 506, name: "Udi", type: "lga", parent_id: 209 },
      { id: 507, name: "Uzo-Uwani", type: "lga", parent_id: 209 },

      { id: 508, name: "Abaji", type: "lga", parent_id: 210 },
      { id: 509, name: "Bwari", type: "lga", parent_id: 210 },
      { id: 510, name: "Gwagwalada", type: "lga", parent_id: 210 },
      { id: 511, name: "Kuje", type: "lga", parent_id: 210 },
      { id: 512, name: "Kwali", type: "lga", parent_id: 210 },
      { id: 513, name: "Municipal Area Council", type: "lga", parent_id: 210 },

      { id: 514, name: "Akko", type: "lga", parent_id: 211 },
      { id: 515, name: "Balanga", type: "lga", parent_id: 211 },
      { id: 516, name: "Billiri", type: "lga", parent_id: 211 },
      { id: 517, name: "Dukku", type: "lga", parent_id: 211 },
      { id: 518, name: "Funakaye", type: "lga", parent_id: 211 },
      { id: 519, name: "Gombe", type: "lga", parent_id: 211 },
      { id: 520, name: "Kaltungo", type: "lga", parent_id: 211 },
      { id: 521, name: "Kwami", type: "lga", parent_id: 211 },
      { id: 522, name: "Nafada", type: "lga", parent_id: 211 },
      { id: 523, name: "Shongom", type: "lga", parent_id: 211 },
      { id: 524, name: "Yamaltu/Deba", type: "lga", parent_id: 211 },

      { id: 525, name: "Aboh Mbaise", type: "lga", parent_id: 212 },
      { id: 526, name: "Ahiazu Mbaise", type: "lga", parent_id: 212 },
      { id: 527, name: "Ehime Mbano", type: "lga", parent_id: 212 },
      { id: 528, name: "Ezinihitte", type: "lga", parent_id: 212 },
      { id: 529, name: "Ideato North", type: "lga", parent_id: 212 },
      { id: 530, name: "Ideato South", type: "lga", parent_id: 212 },
      { id: 531, name: "Ihitte/Uboma", type: "lga", parent_id: 212 },
      { id: 532, name: "Ikeduru", type: "lga", parent_id: 212 },
      { id: 533, name: "Isiala Mbano", type: "lga", parent_id: 212 },
      { id: 534, name: "Isu", type: "lga", parent_id: 212 },
      { id: 535, name: "Mbaitoli", type: "lga", parent_id: 212 },
      { id: 536, name: "Ngor Okpala", type: "lga", parent_id: 212 },
      { id: 537, name: "Njaba", type: "lga", parent_id: 212 },
      { id: 538, name: "Nkwerre", type: "lga", parent_id: 212 },
      { id: 539, name: "Nwangele", type: "lga", parent_id: 212 },
      { id: 540, name: "Obowo", type: "lga", parent_id: 212 },
      { id: 541, name: "Oguta", type: "lga", parent_id: 212 },
      { id: 542, name: "Ohaji/Egbema", type: "lga", parent_id: 212 },
      { id: 543, name: "Okigwe", type: "lga", parent_id: 212 },
      { id: 544, name: "Onuimo", type: "lga", parent_id: 212 },
      { id: 545, name: "Orlu", type: "lga", parent_id: 212 },
      { id: 546, name: "Orsu", type: "lga", parent_id: 212 },
      { id: 547, name: "Oru East", type: "lga", parent_id: 212 },
      { id: 548, name: "Oru West", type: "lga", parent_id: 212 },
      { id: 549, name: "Owerri Municipal", type: "lga", parent_id: 212 },
      { id: 550, name: "Owerri North", type: "lga", parent_id: 212 },
      { id: 551, name: "Owerri West", type: "lga", parent_id: 212 },

      { id: 552, name: "Auyo", type: "lga", parent_id: 213 },
      { id: 553, name: "Babura", type: "lga", parent_id: 213 },
      { id: 554, name: "Biriniwa", type: "lga", parent_id: 213 },
      { id: 555, name: "Birnin Kudu", type: "lga", parent_id: 213 },
      { id: 556, name: "Buji", type: "lga", parent_id: 213 },
      { id: 557, name: "Dutse", type: "lga", parent_id: 213 },
      { id: 558, name: "Gagarawa", type: "lga", parent_id: 213 },
      { id: 559, name: "Garki", type: "lga", parent_id: 213 },
      { id: 560, name: "Gumel", type: "lga", parent_id: 213 },
      { id: 561, name: "Guri", type: "lga", parent_id: 213 },
      { id: 562, name: "Gwaram", type: "lga", parent_id: 213 },
      { id: 563, name: "Gwiwa", type: "lga", parent_id: 213 },
      { id: 564, name: "Hadejia", type: "lga", parent_id: 213 },
      { id: 565, name: "Jahun", type: "lga", parent_id: 213 },
      { id: 566, name: "Kafin Hausa", type: "lga", parent_id: 213 },
      { id: 567, name: "Kaugama", type: "lga", parent_id: 213 },
      { id: 568, name: "Kazaure", type: "lga", parent_id: 213 },
      { id: 569, name: "Kiri Kasama", type: "lga", parent_id: 213 },
      { id: 570, name: "Kiyawa", type: "lga", parent_id: 213 },
      { id: 571, name: "Maigatari", type: "lga", parent_id: 213 },
      { id: 572, name: "Malam Madori", type: "lga", parent_id: 213 },
      { id: 573, name: "Miga", type: "lga", parent_id: 213 },
      { id: 574, name: "Ringim", type: "lga", parent_id: 213 },
      { id: 575, name: "Roni", type: "lga", parent_id: 213 },
      { id: 576, name: "Sule Tankarkar", type: "lga", parent_id: 213 },
      { id: 577, name: "Taura", type: "lga", parent_id: 213 },
      { id: 578, name: "Yankwashi", type: "lga", parent_id: 213 },

      { id: 579, name: "Birnin Gwari", type: "lga", parent_id: 214 },
      { id: 580, name: "Chikun", type: "lga", parent_id: 214 },
      { id: 581, name: "Giwa", type: "lga", parent_id: 214 },
      { id: 582, name: "Igabi", type: "lga", parent_id: 214 },
      { id: 583, name: "Ikara", type: "lga", parent_id: 214 },
      { id: 584, name: "Jaba", type: "lga", parent_id: 214 },
      { id: 585, name: "Jema'a", type: "lga", parent_id: 214 },
      { id: 586, name: "Kachia", type: "lga", parent_id: 214 },
      { id: 587, name: "Kaduna North", type: "lga", parent_id: 214 },
      { id: 588, name: "Kaduna South", type: "lga", parent_id: 214 },
      { id: 589, name: "Kagarko", type: "lga", parent_id: 214 },
      { id: 590, name: "Kajuru", type: "lga", parent_id: 214 },
      { id: 591, name: "Kaura", type: "lga", parent_id: 214 },
      { id: 592, name: "Kauru", type: "lga", parent_id: 214 },
      { id: 593, name: "Kubau", type: "lga", parent_id: 214 },
      { id: 594, name: "Kudan", type: "lga", parent_id: 214 },
      { id: 595, name: "Lere", type: "lga", parent_id: 214 },
      { id: 596, name: "Makarfi", type: "lga", parent_id: 214 },
      { id: 597, name: "Sabon Gari", type: "lga", parent_id: 214 },
      { id: 598, name: "Sanga", type: "lga", parent_id: 214 },
      { id: 599, name: "Soba", type: "lga", parent_id: 214 },
      { id: 600, name: "Zangon Kataf", type: "lga", parent_id: 214 },
      { id: 601, name: "Zaria", type: "lga", parent_id: 214 },

      { id: 602, name: "Ajingi", type: "lga", parent_id: 215 },
      { id: 603, name: "Albasu", type: "lga", parent_id: 215 },
      { id: 604, name: "Bagwai", type: "lga", parent_id: 215 },
      { id: 605, name: "Bebeji", type: "lga", parent_id: 215 },
      { id: 606, name: "Bichi", type: "lga", parent_id: 215 },
      { id: 607, name: "Bunkure", type: "lga", parent_id: 215 },
      { id: 608, name: "Dala", type: "lga", parent_id: 215 },
      { id: 609, name: "Dambatta", type: "lga", parent_id: 215 },
      { id: 610, name: "Dawakin Kudu", type: "lga", parent_id: 215 },
      { id: 611, name: "Dawakin Tofa", type: "lga", parent_id: 215 },
      { id: 612, name: "Doguwa", type: "lga", parent_id: 215 },
      { id: 613, name: "Fagge", type: "lga", parent_id: 215 },
      { id: 614, name: "Gabasawa", type: "lga", parent_id: 215 },
      { id: 615, name: "Garko", type: "lga", parent_id: 215 },
      { id: 616, name: "Garun Mallam", type: "lga", parent_id: 215 },
      { id: 617, name: "Gaya", type: "lga", parent_id: 215 },
      { id: 618, name: "Gezawa", type: "lga", parent_id: 215 },
      { id: 619, name: "Gwale", type: "lga", parent_id: 215 },
      { id: 620, name: "Gwarzo", type: "lga", parent_id: 215 },
      { id: 621, name: "Kabo", type: "lga", parent_id: 215 },
      { id: 622, name: "Kano Municipal", type: "lga", parent_id: 215 },
      { id: 623, name: "Karaye", type: "lga", parent_id: 215 },
      { id: 624, name: "Kibiya", type: "lga", parent_id: 215 },
      { id: 625, name: "Kiru", type: "lga", parent_id: 215 },
      { id: 626, name: "Kumbotso", type: "lga", parent_id: 215 },
      { id: 627, name: "Kunchi", type: "lga", parent_id: 215 },
      { id: 628, name: "Kura", type: "lga", parent_id: 215 },
      { id: 629, name: "Madobi", type: "lga", parent_id: 215 },
      { id: 630, name: "Makoda", type: "lga", parent_id: 215 },
      { id: 631, name: "Minjibir", type: "lga", parent_id: 215 },
      { id: 632, name: "Nasarawa", type: "lga", parent_id: 215 },
      { id: 633, name: "Rano", type: "lga", parent_id: 215 },
      { id: 634, name: "Rimin Gado", type: "lga", parent_id: 215 },
      { id: 635, name: "Rogo", type: "lga", parent_id: 215 },
      { id: 636, name: "Shanono", type: "lga", parent_id: 215 },
      { id: 637, name: "Sumaila", type: "lga", parent_id: 215 },
      { id: 638, name: "Takai", type: "lga", parent_id: 215 },
      { id: 639, name: "Tarauni", type: "lga", parent_id: 215 },
      { id: 640, name: "Tofa", type: "lga", parent_id: 215 },
      { id: 641, name: "Tsanyawa", type: "lga", parent_id: 215 },
      { id: 642, name: "Tudun Wada", type: "lga", parent_id: 215 },
      { id: 643, name: "Ungogo", type: "lga", parent_id: 215 },
      { id: 644, name: "Warawa", type: "lga", parent_id: 215 },
      { id: 645, name: "Wudil", type: "lga", parent_id: 215 },

      { id: 646, name: "Bakori", type: "lga", parent_id: 216 },
      { id: 647, name: "Batagarawa", type: "lga", parent_id: 216 },
      { id: 648, name: "Batsari", type: "lga", parent_id: 216 },
      { id: 649, name: "Baure", type: "lga", parent_id: 216 },
      { id: 650, name: "Bindawa", type: "lga", parent_id: 216 },
      { id: 651, name: "Charanchi", type: "lga", parent_id: 216 },
      { id: 652, name: "Dandume", type: "lga", parent_id: 216 },
      { id: 653, name: "Danja", type: "lga", parent_id: 216 },
      { id: 654, name: "Dan Musa", type: "lga", parent_id: 216 },
      { id: 655, name: "Daura", type: "lga", parent_id: 216 },
      { id: 656, name: "Dutsi", type: "lga", parent_id: 216 },
      { id: 657, name: "Dutsin-Ma", type: "lga", parent_id: 216 },
      { id: 658, name: "Faskari", type: "lga", parent_id: 216 },
      { id: 659, name: "Funtua", type: "lga", parent_id: 216 },
      { id: 660, name: "Ingawa", type: "lga", parent_id: 216 },
      { id: 661, name: "Jibia", type: "lga", parent_id: 216 },
      { id: 662, name: "Kafur", type: "lga", parent_id: 216 },
      { id: 663, name: "Kaita", type: "lga", parent_id: 216 },
      { id: 664, name: "Kankara", type: "lga", parent_id: 216 },
      { id: 665, name: "Kankia", type: "lga", parent_id: 216 },
      { id: 666, name: "Katsina", type: "lga", parent_id: 216 },
      { id: 667, name: "Kurfi", type: "lga", parent_id: 216 },
      { id: 668, name: "Kusada", type: "lga", parent_id: 216 },
      { id: 669, name: "Mai'Adua", type: "lga", parent_id: 216 },
      { id: 670, name: "Malumfashi", type: "lga", parent_id: 216 },
      { id: 671, name: "Mani", type: "lga", parent_id: 216 },
      { id: 672, name: "Mashi", type: "lga", parent_id: 216 },
      { id: 673, name: "Matazu", type: "lga", parent_id: 216 },
      { id: 674, name: "Musawa", type: "lga", parent_id: 216 },
      { id: 675, name: "Rimi", type: "lga", parent_id: 216 },
      { id: 676, name: "Sabuwa", type: "lga", parent_id: 216 },
      { id: 677, name: "Safana", type: "lga", parent_id: 216 },
      { id: 678, name: "Sandamu", type: "lga", parent_id: 216 },
      { id: 679, name: "Zango", type: "lga", parent_id: 216 },

      { id: 680, name: "Aleiro", type: "lga", parent_id: 217 },
      { id: 681, name: "Arewa Dandi", type: "lga", parent_id: 217 },
      { id: 682, name: "Argungu", type: "lga", parent_id: 217 },
      { id: 683, name: "Augie", type: "lga", parent_id: 217 },
      { id: 684, name: "Bagudo", type: "lga", parent_id: 217 },
      { id: 685, name: "Birnin Kebbi", type: "lga", parent_id: 217 },
      { id: 686, name: "Bunza", type: "lga", parent_id: 217 },
      { id: 687, name: "Dandi", type: "lga", parent_id: 217 },
      { id: 688, name: "Fakai", type: "lga", parent_id: 217 },
      { id: 689, name: "Gwandu", type: "lga", parent_id: 217 },
      { id: 690, name: "Jega", type: "lga", parent_id: 217 },
      { id: 691, name: "Kalgo", type: "lga", parent_id: 217 },
      { id: 692, name: "Koko/Besse", type: "lga", parent_id: 217 },
      { id: 693, name: "Maiyama", type: "lga", parent_id: 217 },
      { id: 694, name: "Ngaski", type: "lga", parent_id: 217 },
      { id: 695, name: "Sakaba", type: "lga", parent_id: 217 },
      { id: 696, name: "Shanga", type: "lga", parent_id: 217 },
      { id: 697, name: "Suru", type: "lga", parent_id: 217 },
      { id: 698, name: "Wasagu/Danko", type: "lga", parent_id: 217 },
      { id: 699, name: "Yauri", type: "lga", parent_id: 217 },
      { id: 700, name: "Zuru", type: "lga", parent_id: 217 },

      { id: 701, name: "Adavi", type: "lga", parent_id: 218 },
      { id: 702, name: "Ajaokuta", type: "lga", parent_id: 218 },
      { id: 703, name: "Ankpa", type: "lga", parent_id: 218 },
      { id: 704, name: "Bassa", type: "lga", parent_id: 218 },
      { id: 705, name: "Dekina", type: "lga", parent_id: 218 },
      { id: 706, name: "Ibaji", type: "lga", parent_id: 218 },
      { id: 707, name: "Idah", type: "lga", parent_id: 218 },
      { id: 708, name: "Igalamela-Odolu", type: "lga", parent_id: 218 },
      { id: 709, name: "Ijumu", type: "lga", parent_id: 218 },
      { id: 710, name: "Kabba/Bunu", type: "lga", parent_id: 218 },
      { id: 711, name: "Kogi", type: "lga", parent_id: 218 },
      { id: 712, name: "Lokoja", type: "lga", parent_id: 218 },
      { id: 713, name: "Mopa-Muro", type: "lga", parent_id: 218 },
      { id: 714, name: "Ofu", type: "lga", parent_id: 218 },
      { id: 715, name: "Ogori/Magongo", type: "lga", parent_id: 218 },
      { id: 716, name: "Okehi", type: "lga", parent_id: 218 },
      { id: 717, name: "Okene", type: "lga", parent_id: 218 },
      { id: 718, name: "Olamaboro", type: "lga", parent_id: 218 },
      { id: 719, name: "Omala", type: "lga", parent_id: 218 },
      { id: 720, name: "Yagba East", type: "lga", parent_id: 218 },
      { id: 721, name: "Yagba West", type: "lga", parent_id: 218 },

      { id: 722, name: "Asa", type: "lga", parent_id: 219 },
      { id: 723, name: "Baruten", type: "lga", parent_id: 219 },
      { id: 724, name: "Edu", type: "lga", parent_id: 219 },
      { id: 725, name: "Ekiti", type: "lga", parent_id: 219 },
      { id: 726, name: "Ifelodun", type: "lga", parent_id: 219 },
      { id: 727, name: "Ilorin East", type: "lga", parent_id: 219 },
      { id: 728, name: "Ilorin South", type: "lga", parent_id: 219 },
      { id: 729, name: "Ilorin West", type: "lga", parent_id: 219 },
      { id: 730, name: "Irepodun", type: "lga", parent_id: 219 },
      { id: 731, name: "Isin", type: "lga", parent_id: 219 },
      { id: 732, name: "Kaiama", type: "lga", parent_id: 219 },
      { id: 733, name: "Moro", type: "lga", parent_id: 219 },
      { id: 734, name: "Offa", type: "lga", parent_id: 219 },
      { id: 735, name: "Oke Ero", type: "lga", parent_id: 219 },
      { id: 736, name: "Oyun", type: "lga", parent_id: 219 },
      { id: 737, name: "Pategi", type: "lga", parent_id: 219 },

      { id: 738, name: "Agege", type: "lga", parent_id: 220 },
      { id: 739, name: "Ajeromi-Ifelodun", type: "lga", parent_id: 220 },
      { id: 740, name: "Alimosho", type: "lga", parent_id: 220 },
      { id: 741, name: "Amuwo-Odofin", type: "lga", parent_id: 220 },
      { id: 742, name: "Apapa", type: "lga", parent_id: 220 },
      { id: 743, name: "Badagry", type: "lga", parent_id: 220 },
      { id: 744, name: "Epe", type: "lga", parent_id: 220 },
      { id: 745, name: "Eti-Osa", type: "lga", parent_id: 220 },
      { id: 746, name: "Ibeju-Lekki", type: "lga", parent_id: 220 },
      { id: 747, name: "Ifako-Ijaiye", type: "lga", parent_id: 220 },
      { id: 748, name: "Ikeja", type: "lga", parent_id: 220 },
      { id: 749, name: "Ikorodu", type: "lga", parent_id: 220 },
      { id: 750, name: "Kosofe", type: "lga", parent_id: 220 },
      { id: 751, name: "Lagos Island", type: "lga", parent_id: 220 },
      { id: 752, name: "Lagos Mainland", type: "lga", parent_id: 220 },
      { id: 753, name: "Mushin", type: "lga", parent_id: 220 },
      { id: 754, name: "Ojo", type: "lga", parent_id: 220 },
      { id: 755, name: "Oshodi-Isolo", type: "lga", parent_id: 220 },
      { id: 756, name: "Shomolu", type: "lga", parent_id: 220 },
      { id: 757, name: "Surulere", type: "lga", parent_id: 220 },

      { id: 758, name: "Akwanga", type: "lga", parent_id: 221 },
      { id: 759, name: "Awe", type: "lga", parent_id: 221 },
      { id: 760, name: "Doma", type: "lga", parent_id: 221 },
      { id: 761, name: "Karu", type: "lga", parent_id: 221 },
      { id: 762, name: "Keana", type: "lga", parent_id: 221 },
      { id: 763, name: "Keffi", type: "lga", parent_id: 221 },
      { id: 764, name: "Kokona", type: "lga", parent_id: 221 },
      { id: 765, name: "Lafia", type: "lga", parent_id: 221 },
      { id: 766, name: "Nasarawa", type: "lga", parent_id: 221 },
      { id: 767, name: "Nasarawa Egon", type: "lga", parent_id: 221 },
      { id: 768, name: "Obi", type: "lga", parent_id: 221 },
      { id: 769, name: "Toto", type: "lga", parent_id: 221 },
      { id: 770, name: "Wamba", type: "lga", parent_id: 221 },

      { id: 771, name: "Agaie", type: "lga", parent_id: 222 },
      { id: 772, name: "Agwara", type: "lga", parent_id: 222 },
      { id: 773, name: "Bida", type: "lga", parent_id: 222 },
      { id: 774, name: "Borgu", type: "lga", parent_id: 222 },
      { id: 775, name: "Bosso", type: "lga", parent_id: 222 },
      { id: 776, name: "Chanchaga", type: "lga", parent_id: 222 },
      { id: 777, name: "Edati", type: "lga", parent_id: 222 },
      { id: 778, name: "Gbako", type: "lga", parent_id: 222 },
      { id: 779, name: "Gurara", type: "lga", parent_id: 222 },
      { id: 780, name: "Katcha", type: "lga", parent_id: 222 },
      { id: 781, name: "Kontagora", type: "lga", parent_id: 222 },
      { id: 782, name: "Lapai", type: "lga", parent_id: 222 },
      { id: 783, name: "Lavun", type: "lga", parent_id: 222 },
      { id: 784, name: "Magama", type: "lga", parent_id: 222 },
      { id: 785, name: "Mariga", type: "lga", parent_id: 222 },
      { id: 786, name: "Mashegu", type: "lga", parent_id: 222 },
      { id: 787, name: "Mokwa", type: "lga", parent_id: 222 },
      { id: 788, name: "Muya", type: "lga", parent_id: 222 },
      { id: 789, name: "Paikoro", type: "lga", parent_id: 222 },
      { id: 790, name: "Rafi", type: "lga", parent_id: 222 },
      { id: 791, name: "Rijau", type: "lga", parent_id: 222 },
      { id: 792, name: "Shiroro", type: "lga", parent_id: 222 },
      { id: 793, name: "Suleja", type: "lga", parent_id: 222 },
      { id: 794, name: "Tafa", type: "lga", parent_id: 222 },
      { id: 795, name: "Wushishi", type: "lga", parent_id: 222 },

      { id: 796, name: "Abeokuta North", type: "lga", parent_id: 223 },
      { id: 797, name: "Abeokuta South", type: "lga", parent_id: 223 },
      { id: 798, name: "Ado-Odo/Ota", type: "lga", parent_id: 223 },
      { id: 799, name: "Egbado North", type: "lga", parent_id: 223 },
      { id: 800, name: "Egbado South", type: "lga", parent_id: 223 },
      { id: 801, name: "Ewekoro", type: "lga", parent_id: 223 },
      { id: 802, name: "Ifo", type: "lga", parent_id: 223 },
      { id: 803, name: "Ijebu East", type: "lga", parent_id: 223 },
      { id: 804, name: "Ijebu North", type: "lga", parent_id: 223 },
      { id: 805, name: "Ijebu North East", type: "lga", parent_id: 223 },
      { id: 806, name: "Ijebu Ode", type: "lga", parent_id: 223 },
      { id: 807, name: "Ikenne", type: "lga", parent_id: 223 },
      { id: 808, name: "Imeko Afon", type: "lga", parent_id: 223 },
      { id: 809, name: "Ipokia", type: "lga", parent_id: 223 },
      { id: 810, name: "Obafemi Owode", type: "lga", parent_id: 223 },
      { id: 811, name: "Odeda", type: "lga", parent_id: 223 },
      { id: 812, name: "Odogbolu", type: "lga", parent_id: 223 },
      { id: 813, name: "Ogun Waterside", type: "lga", parent_id: 223 },
      { id: 814, name: "Remo North", type: "lga", parent_id: 223 },
      { id: 815, name: "Sagamu", type: "lga", parent_id: 223 },

      { id: 816, name: "Akoko North-East", type: "lga", parent_id: 224 },
      { id: 817, name: "Akoko North-West", type: "lga", parent_id: 224 },
      { id: 818, name: "Akoko South-East", type: "lga", parent_id: 224 },
      { id: 819, name: "Akoko South-West", type: "lga", parent_id: 224 },
      { id: 820, name: "Akure North", type: "lga", parent_id: 224 },
      { id: 821, name: "Akure South", type: "lga", parent_id: 224 },
      { id: 822, name: "Ese Odo", type: "lga", parent_id: 224 },
      { id: 823, name: "Idanre", type: "lga", parent_id: 224 },
      { id: 824, name: "Ifedore", type: "lga", parent_id: 224 },
      { id: 825, name: "Ilaje", type: "lga", parent_id: 224 },
      { id: 826, name: "Ile Oluji/Okeigbo", type: "lga", parent_id: 224 },
      { id: 827, name: "Irele", type: "lga", parent_id: 224 },
      { id: 828, name: "Odigbo", type: "lga", parent_id: 224 },
      { id: 829, name: "Okitipupa", type: "lga", parent_id: 224 },
      { id: 830, name: "Ondo East", type: "lga", parent_id: 224 },
      { id: 831, name: "Ondo West", type: "lga", parent_id: 224 },
      { id: 832, name: "Ose", type: "lga", parent_id: 224 },
      { id: 833, name: "Owo", type: "lga", parent_id: 224 },

      { id: 834, name: "Atakunmosa East", type: "lga", parent_id: 225 },
      { id: 835, name: "Atakunmosa West", type: "lga", parent_id: 225 },
      { id: 836, name: "Aiyedaade", type: "lga", parent_id: 225 },
      { id: 837, name: "Aiyedire", type: "lga", parent_id: 225 },
      { id: 838, name: "Boluwaduro", type: "lga", parent_id: 225 },
      { id: 839, name: "Boripe", type: "lga", parent_id: 225 },
      { id: 840, name: "Ede North", type: "lga", parent_id: 225 },
      { id: 841, name: "Ede South", type: "lga", parent_id: 225 },
      { id: 842, name: "Egbedore", type: "lga", parent_id: 225 },
      { id: 843, name: "Ejigbo", type: "lga", parent_id: 225 },
      { id: 844, name: "Ife Central", type: "lga", parent_id: 225 },
      { id: 845, name: "Ife East", type: "lga", parent_id: 225 },
      { id: 846, name: "Ife North", type: "lga", parent_id: 225 },
      { id: 847, name: "Ife South", type: "lga", parent_id: 225 },
      { id: 848, name: "Ifedayo", type: "lga", parent_id: 225 },
      { id: 849, name: "Ifelodun", type: "lga", parent_id: 225 },
      { id: 850, name: "Ila", type: "lga", parent_id: 225 },
      { id: 851, name: "Ilesa East", type: "lga", parent_id: 225 },
      { id: 852, name: "Ilesa West", type: "lga", parent_id: 225 },
      { id: 853, name: "Irepodun", type: "lga", parent_id: 225 },
      { id: 854, name: "Irewole", type: "lga", parent_id: 225 },
      { id: 855, name: "Isokan", type: "lga", parent_id: 225 },
      { id: 856, name: "Iwo", type: "lga", parent_id: 225 },
      { id: 857, name: "Obokun", type: "lga", parent_id: 225 },
      { id: 858, name: "Odo Otin", type: "lga", parent_id: 225 },
      { id: 859, name: "Ola Oluwa", type: "lga", parent_id: 225 },
      { id: 860, name: "Olorunda", type: "lga", parent_id: 225 },
      { id: 861, name: "Oriade", type: "lga", parent_id: 225 },
      { id: 862, name: "Orolu", type: "lga", parent_id: 225 },
      { id: 863, name: "Osogbo", type: "lga", parent_id: 225 },

      { id: 864, name: "Afijio", type: "lga", parent_id: 226 },
      { id: 865, name: "Akinyele", type: "lga", parent_id: 226 },
      { id: 866, name: "Atiba", type: "lga", parent_id: 226 },
      { id: 867, name: "Atisbo", type: "lga", parent_id: 226 },
      { id: 868, name: "Egbeda", type: "lga", parent_id: 226 },
      { id: 869, name: "Ibadan North", type: "lga", parent_id: 226 },
      { id: 870, name: "Ibadan North-East", type: "lga", parent_id: 226 },
      { id: 871, name: "Ibadan North-West", type: "lga", parent_id: 226 },
      { id: 872, name: "Ibadan South-East", type: "lga", parent_id: 226 },
      { id: 873, name: "Ibadan South-West", type: "lga", parent_id: 226 },
      { id: 874, name: "Ibarapa Central", type: "lga", parent_id: 226 },
      { id: 875, name: "Ibarapa East", type: "lga", parent_id: 226 },
      { id: 876, name: "Ibarapa North", type: "lga", parent_id: 226 },
      { id: 877, name: "Ido", type: "lga", parent_id: 226 },
      { id: 878, name: "Irepo", type: "lga", parent_id: 226 },
      { id: 879, name: "Iseyin", type: "lga", parent_id: 226 },
      { id: 880, name: "Itesiwaju", type: "lga", parent_id: 226 },
      { id: 881, name: "Iwajowa", type: "lga", parent_id: 226 },
      { id: 882, name: "Kajola", type: "lga", parent_id: 226 },
      { id: 883, name: "Lagelu", type: "lga", parent_id: 226 },
      { id: 884, name: "Ogbomosho North", type: "lga", parent_id: 226 },
      { id: 885, name: "Ogbomosho South", type: "lga", parent_id: 226 },
      { id: 886, name: "Ogo Oluwa", type: "lga", parent_id: 226 },
      { id: 887, name: "Olorunsogo", type: "lga", parent_id: 226 },
      { id: 888, name: "Oluyole", type: "lga", parent_id: 226 },
      { id: 889, name: "Ona Ara", type: "lga", parent_id: 226 },
      { id: 890, name: "Orelope", type: "lga", parent_id: 226 },
      { id: 891, name: "Ori Ire", type: "lga", parent_id: 226 },
      { id: 892, name: "Oyo East", type: "lga", parent_id: 226 },
      { id: 893, name: "Oyo West", type: "lga", parent_id: 226 },
      { id: 894, name: "Saki East", type: "lga", parent_id: 226 },
      { id: 895, name: "Saki West", type: "lga", parent_id: 226 },
      { id: 896, name: "Surulere", type: "lga", parent_id: 226 },

      { id: 897, name: "Barkin Ladi", type: "lga", parent_id: 227 },
      { id: 898, name: "Bassa", type: "lga", parent_id: 227 },
      { id: 899, name: "Bokkos", type: "lga", parent_id: 227 },
      { id: 900, name: "Jos East", type: "lga", parent_id: 227 },
      { id: 901, name: "Jos North", type: "lga", parent_id: 227 },
      { id: 902, name: "Jos South", type: "lga", parent_id: 227 },
      { id: 903, name: "Kanam", type: "lga", parent_id: 227 },
      { id: 904, name: "Kanke", type: "lga", parent_id: 227 },
      { id: 905, name: "Langtang North", type: "lga", parent_id: 227 },
      { id: 906, name: "Langtang South", type: "lga", parent_id: 227 },
      { id: 907, name: "Mangu", type: "lga", parent_id: 227 },
      { id: 908, name: "Mikang", type: "lga", parent_id: 227 },
      { id: 909, name: "Pankshin", type: "lga", parent_id: 227 },
      { id: 910, name: "Qua'an Pan", type: "lga", parent_id: 227 },
      { id: 911, name: "Riyom", type: "lga", parent_id: 227 },
      { id: 912, name: "Shendam", type: "lga", parent_id: 227 },
      { id: 913, name: "Wase", type: "lga", parent_id: 227 },

      { id: 914, name: "Abua/Odual", type: "lga", parent_id: 228 },
      { id: 915, name: "Ahoada East", type: "lga", parent_id: 228 },
      { id: 916, name: "Ahoada West", type: "lga", parent_id: 228 },
      { id: 917, name: "Akuku-Toru", type: "lga", parent_id: 228 },
      { id: 918, name: "Andoni", type: "lga", parent_id: 228 },
      { id: 919, name: "Asari-Toru", type: "lga", parent_id: 228 },
      { id: 920, name: "Bonny", type: "lga", parent_id: 228 },
      { id: 921, name: "Degema", type: "lga", parent_id: 228 },
      { id: 922, name: "Eleme", type: "lga", parent_id: 228 },
      { id: 923, name: "Emohua", type: "lga", parent_id: 228 },
      { id: 924, name: "Etche", type: "lga", parent_id: 228 },
      { id: 925, name: "Gokana", type: "lga", parent_id: 228 },
      { id: 926, name: "Ikwerre", type: "lga", parent_id: 228 },
      { id: 927, name: "Khana", type: "lga", parent_id: 228 },
      { id: 928, name: "Obio/Akpor", type: "lga", parent_id: 228 },
      { id: 929, name: "Ogba/Egbema/Ndoni", type: "lga", parent_id: 228 },
      { id: 930, name: "Ogu/Bolo", type: "lga", parent_id: 228 },
      { id: 931, name: "Okrika", type: "lga", parent_id: 228 },
      { id: 932, name: "Omuma", type: "lga", parent_id: 228 },
      { id: 933, name: "Opobo/Nkoro", type: "lga", parent_id: 228 },
      { id: 934, name: "Oyigbo", type: "lga", parent_id: 228 },
      { id: 935, name: "Port Harcourt", type: "lga", parent_id: 228 },
      { id: 936, name: "Tai", type: "lga", parent_id: 228 },

      { id: 937, name: "Binji", type: "lga", parent_id: 229 },
      { id: 938, name: "Bodinga", type: "lga", parent_id: 229 },
      { id: 939, name: "Dange-Shuni", type: "lga", parent_id: 229 },
      { id: 940, name: "Gada", type: "lga", parent_id: 229 },
      { id: 941, name: "Goronyo", type: "lga", parent_id: 229 },
      { id: 942, name: "Gudu", type: "lga", parent_id: 229 },
      { id: 943, name: "Gwadabawa", type: "lga", parent_id: 229 },
      { id: 944, name: "Illela", type: "lga", parent_id: 229 },
      { id: 945, name: "Isa", type: "lga", parent_id: 229 },
      { id: 946, name: "Kebbe", type: "lga", parent_id: 229 },
      { id: 947, name: "Kware", type: "lga", parent_id: 229 },
      { id: 948, name: "Rabah", type: "lga", parent_id: 229 },
      { id: 949, name: "Sabon Birni", type: "lga", parent_id: 229 },
      { id: 950, name: "Shagari", type: "lga", parent_id: 229 },
      { id: 951, name: "Silame", type: "lga", parent_id: 229 },
      { id: 952, name: "Sokoto North", type: "lga", parent_id: 229 },
      { id: 953, name: "Sokoto South", type: "lga", parent_id: 229 },
      { id: 954, name: "Tambuwal", type: "lga", parent_id: 229 },
      { id: 955, name: "Tangaza", type: "lga", parent_id: 229 },
      { id: 956, name: "Tureta", type: "lga", parent_id: 229 },
      { id: 957, name: "Wamako", type: "lga", parent_id: 229 },
      { id: 958, name: "Wurno", type: "lga", parent_id: 229 },
      { id: 959, name: "Yabo", type: "lga", parent_id: 229 },

      { id: 960, name: "Ardo-Kola", type: "lga", parent_id: 230 },
      { id: 961, name: "Bali", type: "lga", parent_id: 230 },
      { id: 962, name: "Donga", type: "lga", parent_id: 230 },
      { id: 963, name: "Gashaka", type: "lga", parent_id: 230 },
      { id: 964, name: "Gassol", type: "lga", parent_id: 230 },
      { id: 965, name: "Ibi", type: "lga", parent_id: 230 },
      { id: 966, name: "Jalingo", type: "lga", parent_id: 230 },
      { id: 967, name: "Karim Lamido", type: "lga", parent_id: 230 },
      { id: 968, name: "Kumi", type: "lga", parent_id: 230 },
      { id: 969, name: "Lau", type: "lga", parent_id: 230 },
      { id: 970, name: "Sardauna", type: "lga", parent_id: 230 },
      { id: 971, name: "Takum", type: "lga", parent_id: 230 },
      { id: 972, name: "Ussa", type: "lga", parent_id: 230 },
      { id: 973, name: "Wukari", type: "lga", parent_id: 230 },
      { id: 974, name: "Yorro", type: "lga", parent_id: 230 },
      { id: 975, name: "Zing", type: "lga", parent_id: 230 },

      { id: 976, name: "Bade", type: "lga", parent_id: 231 },
      { id: 977, name: "Bursari", type: "lga", parent_id: 231 },
      { id: 978, name: "Damaturu", type: "lga", parent_id: 231 },
      { id: 979, name: "Fika", type: "lga", parent_id: 231 },
      { id: 980, name: "Fune", type: "lga", parent_id: 231 },
      { id: 981, name: "Geidam", type: "lga", parent_id: 231 },
      { id: 982, name: "Gujba", type: "lga", parent_id: 231 },
      { id: 983, name: "Gulani", type: "lga", parent_id: 231 },
      { id: 984, name: "Jakusko", type: "lga", parent_id: 231 },
      { id: 985, name: "Karasuwa", type: "lga", parent_id: 231 },
      { id: 986, name: "Machina", type: "lga", parent_id: 231 },
      { id: 987, name: "Nangere", type: "lga", parent_id: 231 },
      { id: 988, name: "Nguru", type: "lga", parent_id: 231 },
      { id: 989, name: "Potiskum", type: "lga", parent_id: 231 },
      { id: 990, name: "Tarmuwa", type: "lga", parent_id: 231 },
      { id: 991, name: "Yunusari", type: "lga", parent_id: 231 },
      { id: 992, name: "Yusufari", type: "lga", parent_id: 231 },

      { id: 993, name: "Anka", type: "lga", parent_id: 232 },
      { id: 994, name: "Bakura", type: "lga", parent_id: 232 },
      { id: 995, name: "Birnin Magaji", type: "lga", parent_id: 232 },
      { id: 996, name: "Bukkuyum", type: "lga", parent_id: 232 },
      { id: 997, name: "Bungudu", type: "lga", parent_id: 232 },
      { id: 998, name: "Gummi", type: "lga", parent_id: 232 },
      { id: 999, name: "Gusau", type: "lga", parent_id: 232 },
      { id: 1000, name: "Kaura Namoda", type: "lga", parent_id: 232 },
      { id: 1001, name: "Maradun", type: "lga", parent_id: 232 },
      { id: 1002, name: "Maru", type: "lga", parent_id: 232 },
      { id: 1003, name: "Shinkafi", type: "lga", parent_id: 232 },
      { id: 1004, name: "Talata Mafara", type: "lga", parent_id: 232 },
      { id: 1005, name: "Tsafe", type: "lga", parent_id: 232 },
      { id: 1006, name: "Zurmi", type: "lga", parent_id: 232 },
    ],
    skipDuplicates: true,
  });

  // ======================
  // ROLES
  // ======================
  // await prisma.roles.createMany({
  //   data: [
  //     { id: 1, name: "Admin", description: "" },
  //     { id: 2, name: "CEO", description: "" },
  //     { id: 3, name: "User", description: "" },
  //   ],
  // });

  // ======================
  // ROLES
  // ======================
  // await prisma.statuses.createMany({
  //   data: [
  //     { id: 1, name: "Active", description: "" },
  //     { id: 2, name: "Pending", description: "" },
  //   ],
  // });

  // ======================
  // POSTS
  // ======================
  await prisma.posts.createMany({
    data: [
      {
        id: 1,
        user_id: 4,
        category: "travel",
        title: "A Quiet Morning in Oban",
        text: "When we launched our first product, I told myself we would not hire salespeople until we had a repeatable funnel. We were two founders, a small marketing budget, and a mountain of cold outreach to do. The first six months were brutal — meetings that led nowhere, demo fatigue, and a constant scramble to justify our runway decisions. But instead of treating sales as a black box, we treated it like a product to be iterated.\\n\\nFirst, we mapped the full buyer journey end to end: discovery channels, lead qualification criteria, onboarding success triggers, and churn signals. We instrumented every point with lightweight analytics and started running weekly experiments. The key insight was that a small set of content assets (one deep-case study, a 12-minute product walkthrough, and a template we gave away) generated nearly 60% of our qualified leads when amplified with targeted ads and warm email sequences.\\n\\nNext, qualification rules moved out of subjective judgment and into explicit criteria. If a prospect hit two or more product-fit signals and had a clear timeframe, they moved to the demo queue. Otherwise they entered a nurture flow. That simple change reduced our demo time by 40% and eliminated half the “talkative but unready” prospects. Finally, we standardized the demo experience into a 20-minute playbook focused on outcomes, not features.\\n\\nThe result: by month nine, our conversion from demo to paid had improved enough that hiring a single SDR made sense. But crucially, the SDR relied on the repeatable funnel we had built — playbooks, qualification flags, and content-driven outreach. If you’re a founder trying to delay headcount, treat sales like a product: instrument, iterate, and automate the parts that don’t require nuanced human judgement.",
        published: true,
      },
      {
        id: 2,
        user_id: 2,
        category: "tech",
        title: "Trying Out a New UI Pattern",
        text: "Setting price is as much behavioral as it is arithmetic. In our earliest experiments we priced purely on cost plus margin and were surprised by the results: a lower tier with too many features cannibalized uptake for the higher tier, and enterprise prospects ignored our 'standard' tier entirely.\\n\\nThe work that changed our approach combined simple experiments with classic behavioral nudges. We introduced a decoy plan, packaged features into outcome-focused tiers (starter: quick wins, growth: measurable ROI, enterprise: customization & support), and tested anchoring by presenting the enterprise plan first. Within a month we observed a significant shift in choice architecture — more customers self-selected into the growth tier which delivered the best lifetime value.\\n\\nCrucial to success was measuring real signals: time to first value, churn in month three, and support touch frequency. Pricing isn't fixed; it is dynamic and should be paired with product improvements and tightened onboarding flows. For founders, the practical takeaway is simple: price for outcomes, not hours. Test the anchors, watch for churn regressors, and be ready to simplify offerings into clear stories that buyers can understand quickly.",
        published: true,
      },
      {
        id: 3,
        user_id: 7,
        category: "lifestyle",
        title: "Minimalism Isn't About Owning Less",
        text: "Turning a side project into a sustainable business is equal parts discipline and leverage. My co-founder started a content-heavy newsletter while working full time; I joined later and helped turn the traction into a productized service. The playbook we used focused on three pillars: productize a core service, systemize distribution, and limit scope until revenue proved repeatable.\\n\\nProductization meant extracting the most valuable outcome clients paid for (not the full bespoke service) and building a repeatable deliverable. Systemizing distribution involved a referral engine embedded into onboarding — small prompts asking early customers for introductions in exchange for discounts.\\n\\nThe hardest part for many founders is saying no. We resisted feature creep aggressively in the first 12 months and focused on a narrow vertical where our messages resonated. That focus allowed us to optimize processes and margins. Today, the business supports two full-time employees and a modest local ad spend that reliably brings in leads. The lesson: start with a repeatable offer, create predictable paths for discovery and referrals, and don’t expand until the unit economics are proven.",
        published: false,
      },
      {
        id: 4,
        user_id: 9,
        category: "food",
        title: "Homemade Jollof Triumph",
        text: "Churn kills startups quietly. Many teams obsess over acquisition and only later realize that retention is the real lever for sustainable growth. In our first year, we identified three practical interventions that materially reduced churn: better onboarding sequences, clearer success milestones, and early intervention playbooks for at-risk accounts.\\n\\nOnboarding matters more than elegant design. We replaced a feature walkthrough with an outcomes-driven checklist that users could complete in under 20 minutes. Each checklist completion fed into our success dashboard and triggered targeted in-app tips. Second, we defined measurable success milestones for the product — a simple set of actions that predicted long-term retention. When users failed to hit milestone one within seven days, the system created a task for a customer success check-in.\\n\\nLastly, the intervention playbook standardized outreach for at-risk accounts: a sequence of personalized emails, an offer of a live short session, and guided documentation. By combining these three steps, we saw a reduction in churn of roughly 18% over two quarters. The pragmatic takeaway is to instrument signals early and design low-friction, automated interventions before human touch is necessary.",
        published: true,
      },
      {
        id: 5,
        user_id: 8,
        category: "fitness",
        title: "First 5K in Months",
        text: "Scale exposes the cracks in process and values. We grew from 3 to 18 people in under a year and learned quickly that hiring without operational guardrails leads to drift. Operational discipline doesn't mean bureaucracy — it means defined decision rights, onboarding checklists, and a cadence of communication that preserves culture.\\n\\nWe adopted three practices: weekly leadership syncs with a clear agenda, written decision logs for non-trivial calls, and a 'buddy' onboarding system for new hires that pairs culture exposure with practical training. These changes cut onboarding time by nearly half and reduced errors created by inconsistent handoffs.\\n\\nGuardrails also include how you hire. We tightened job briefs to reflect outcomes and introduced structured interviews focused on past behavior rather than hypothetical answers. Structure provided predictability and helped us scale while keeping core values visible across teams.",
        published: true,
      },
      {
        id: 6,
        user_id: 4,
        category: "motoring",
        title: "Night Drive Reflections",
        text: "Everyone talks about product-market fit, but few teams are disciplined about how they do discovery. We replaced ad-hoc customer calls with a repeatable discovery framework: hypothesis, interview guide, test, and measure. Every interview had three consistent sections — problem validation, solution reservation, and purchase intent — which made insights comparable across prospects.\\n\\nWe tracked signals that correlated with subsequent purchase behavior and discovered surprising patterns: certain job titles had four times higher willingness to pay and specific phrasing in pain statements predicted urgency. Those signals helped us re-prioritize roadmap items and tailor messaging to the highest-converting segments.\\n\\nDiscovery is not a one-off; it is an operational rhythm. By institutionalizing it, we turned qualitative interviews into quantifiable signals that informed product decisions and improved acquisition efficiency.",
        published: false,
      },
      {
        id: 7,
        user_id: 1,
        category: "coding",
        title: "TypeScript Saved Me Again",
        text: "Hiring a first product manager is a pivotal decision. Too junior and they will struggle with prioritization; too senior and they may expect headcount and processes you don't have. We solved this by writing a role-first brief that emphasized outcomes over activities: deliver a product roadmap that leads to X% activation increase, reduce onboarding time by Y, and own feature prioritization in collaboration with engineering and sales.\\n\\nInterviews focused on past examples of trade-offs and prioritization rather than hypothetical frameworks. We asked candidates to walk through specific decisions they had made, the data used, stakeholders involved, and the measured outcome. This approach revealed practical experience over theoretical knowledge.\\n\\nOnce hired, the PM had a 90-day plan jointly signed by the CEO outlining success metrics and stakeholder commitments. The clarity of expectations and early wins helped the hire integrate quickly and deliver measurable impact.",
        published: true,
      },
      {
        id: 8,
        user_id: 7,
        category: "parenting",
        title: "Kids and Chaos",
        text: "Paid acquisition can drive growth quickly but it is rarely sustainable at early stages. We experimented with three non-paid channels that proved durable: strategic partnerships, content with SEO compounding, and product-led growth hooks.\\n\\nPartnerships required a service mindset — we identified companies whose customers needed our product and created co-marketing plays that delivered value to both sides. SEO content initially required an investment but compounded over time, delivering a steady stream of qualified leads. The product-led hooks focused on creating immediate value within the product and subtle viral mechanics encouraging sharing.\\n\\nA disciplined measurement stack allowed us to shift resources toward channels with positive unit economics. The goal is not to avoid paid channels, but to treat them as amplifiers of proven organic signals. When organic channels work, paid can be deployed to scale them efficiently.",
        published: true,
      },
      {
        id: 9,
        user_id: 9,
        category: "finance",
        title: "Budget Reset",
        text: "Cutting back on subscriptions I don't use. Small changes add up fast.",
        published: false,
      },
      {
        id: 10,
        user_id: 8,
        category: "photography",
        title: "Chasing Light",
        text: "Captured a perfect golden-hour shot by accident. Sometimes luck > skill.",
        published: true,
      },
    ],
    skipDuplicates: true,
  });

  // ======================
  // COMMENTS
  // ======================
  await prisma.comments.createMany({
    data: [
      {
        id: 1,
        user_id: null,
        guest: "Guest Dana",
        post_id: 2,
        parent_id: 9,
        comment: "Security is key!",
      },
      {
        id: 2,
        user_id: 9,
        guest: null,
        post_id: 4,
        parent_id: 10,
        comment: "Let me know how it goes!",
      },
      {
        id: 3,
        user_id: 8,
        guest: null,
        post_id: 2,
        parent_id: null,
        comment: "Cloud architecture explained clearly!",
      },
      {
        id: 4,
        user_id: 4,
        guest: null,
        post_id: 6,
        parent_id: null,
        comment: "Nice JS tricks, I learned something new.",
      },
      {
        id: 5,
        user_id: null,
        guest: "Guest Hannah",
        post_id: 7,
        parent_id: 9,
        comment: "I love these principles.",
      },
      {
        id: 6,
        user_id: 7,
        guest: null,
        post_id: 4,
        parent_id: null,
        comment: "CI/CD pipelines are a lifesaver!",
      },
      {
        id: 7,
        user_id: null,
        guest: "Guest Frank",
        post_id: 4,
        parent_id: 6,
        comment: "Totally agree!",
      },
      {
        id: 8,
        user_id: 2,
        guest: null,
        post_id: 3,
        parent_id: 10,
        comment: "The obvious one of course.",
      },
      {
        id: 9,
        user_id: null,
        guest: "Guest Charlie",
        post_id: 2,
        parent_id: null,
        comment: "Helpful visual diagrams.",
      },
      {
        id: 10,
        user_id: null,
        guest: "Guest Ian",
        post_id: 9,
        parent_id: null,
        comment: "React performance tips are awesome!",
      },
      {
        id: 11,
        user_id: null,
        guest: "Anonymous",
        post_id: 3,
        parent_id: 13,
        comment: "What are you saying?",
      },
      {
        id: 12,
        user_id: 4,
        guest: null,
        post_id: 4,
        parent_id: null,
        comment: "Great post! Learned a lot.",
      },
      {
        id: 13,
        user_id: null,
        guest: "Guest Eve",
        post_id: 3,
        parent_id: null,
        comment: "Thanks for these tips!",
      },
      {
        id: 14,
        user_id: null,
        guest: "Guest Grace",
        post_id: 5,
        parent_id: null,
        comment: "Optimizing queries saves so much time!",
      },
      {
        id: 15,
        user_id: 8,
        guest: null,
        post_id: 3,
        parent_id: null,
        comment: "Daily habits really help coding growth.",
      },
      {
        id: 16,
        user_id: 8,
        guest: null,
        post_id: 5,
        parent_id: 14,
        comment: "Exactly, indexes are key.",
      },
      {
        id: 17,
        user_id: 1,
        guest: null,
        post_id: 4,
        parent_id: null,
        comment: "Excited to try these tips!",
      },
      {
        id: 18,
        user_id: 7,
        guest: null,
        post_id: 10,
        parent_id: null,
        comment: "Design systems make teamwork easier.",
      },
      {
        id: 19,
        user_id: 2,
        guest: null,
        post_id: 7,
        parent_id: null,
        comment: "UI/UX design tips are great!",
      },
      {
        id: 20,
        user_id: 4,
        guest: null,
        post_id: 3,
        parent_id: 13,
        comment: "Which tip did you like most?",
      },
      {
        id: 21,
        user_id: 7,
        guest: null,
        post_id: 8,
        parent_id: null,
        comment: "Motivation is hard, these tips help!",
      },
      {
        id: 22,
        user_id: null,
        guest: "Guest Alice",
        post_id: 1,
        parent_id: null,
        comment: "Thanks for sharing!",
      },
      {
        id: 23,
        user_id: null,
        guest: "Guest Bob",
        post_id: 1,
        parent_id: 22,
        comment: "I agree with you!",
      },
      {
        id: 24,
        user_id: null,
        guest: "Guest Jack",
        post_id: 1,
        parent_id: null,
        comment: "REST APIs are easier to understand with this guide.",
      },
      {
        id: 25,
        user_id: 9,
        guest: null,
        post_id: 2,
        parent_id: null,
        comment: "Can you expand on security considerations?",
      },
    ],
    skipDuplicates: true,
  });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
